{
 "title": "Ping & Latency",
 "tags": [ "ping" ],
 "refresh": "10s",
 "panels": [
  {
   "title": "Targets",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 4, "h": 4 },
   "targets": [
    { "expr": "count(ping_up)" }
   ]
  },
  {
   "title": "Latency (s)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 4, "w": 24, "h": 10 },
   "targets": [
    { "expr": "ping_latency_seconds" },
    { "expr": "ping_latency_threshold_seconds" }
   ]
  },
  {
   "title": "Up/Down",
   "type": "state-timeline",
   "gridPos": { "x": 0, "y": 14, "w": 24, "h": 8 },
   "targets": [
    { "expr": "ping_up" }
   ]
  }
 ]
}